version: '3.8'

services:
  fichas-tecnicas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fichas-tecnicas-app
    environment:
      # Copy your environment variables here
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - EXA_API_KEY=${EXA_API_KEY}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount output directory to host
      - ./output:/app/output
      # Mount input files
      - ./input_examples:/app/input_examples
      - ./files:/app/files
      # Mount configs (read-only)
      - ./config:/app/config:ro
    working_dir: /app
    networks:
      - fichas-network
    restart: unless-stopped
    # Uncomment if you want to run interactively
    # stdin_open: true
    # tty: true

  # Optional: Add a web interface service if needed
  # web-interface:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fichas-web
  #   command: python -m nicegui
  #   ports:
  #     - "8080:8000"
  #   environment:
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #   volumes:
  #     - ./output:/app/output
  #   networks:
  #     - fichas-network
  #   depends_on:
  #     - fichas-tecnicas

networks:
  fichas-network:
    driver: bridge

volumes:
  output-data:
    driver: local