# Railway-compatible Docker Compose configuration
version: '3.8'

services:
  fichas-tecnicas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fichas-tecnicas-app
    environment:
      # Railway environment variables
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST:-https://cloud.langfuse.com}
      - EXA_API_KEY=${EXA_API_KEY}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PORT=${PORT:-8000}
      # Railway deployment variables
      - RAILWAY_ENVIRONMENT=${RAILWAY_ENVIRONMENT:-development}
      - RAILWAY_PROJECT_ID=${RAILWAY_PROJECT_ID}
      - RAILWAY_SERVICE_ID=${RAILWAY_SERVICE_ID}
    volumes:
      # Persistent volumes for Railway
      - output-data:/app/output
      - input-data:/app/input_examples
      - files-data:/app/files
      - ./config:/app/config:ro
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    working_dir: /app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Streamlit web interface for Railway
  web-interface:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fichas-web
    command: ["python", "-m", "streamlit", "run", "streamlit_app.py", "--server.port=${WEB_PORT:-8080}", "--server.address=0.0.0.0"]
    ports:
      - "${WEB_PORT:-8080}:${WEB_PORT:-8080}"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST:-https://cloud.langfuse.com}
      - EXA_API_KEY=${EXA_API_KEY}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - WEB_PORT=${WEB_PORT:-8080}
    volumes:
      - output-data:/app/output
      - input-data:/app/input_examples
      - files-data:/app/files
      - ./config:/app/config:ro
    restart: unless-stopped
    depends_on:
      - fichas-tecnicas
    profiles:
      - web

volumes:
  # Persistent volumes for Railway deployment
  output-data:
    driver: local
  input-data:
    driver: local
  files-data:
    driver: local